apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: kube-apiserver-scale
  namespace: shoot--timebertt--sharding
spec:
  failurePolicy: Ignore
  # schema validation doesn't seem to work in combination with the /scale subresource, disable it for now
  schemaValidation: false
  rules:
  # set static replicas on kube-apiserver to ensure similar evaluation environment between load test runs
  - name: replicas-scale
    match:
      any:
      - resources:
          # mutate scale requests by HPA
          kinds:
          - Deployment/scale
          # the Scale subresource doesn't have the original resource's labels -> we have to match by name
          names:
          - kube-apiserver
    preconditions:
      all:
      # Only patch spec.replicas if the control plane is not hibernated, i.e., if spec.replicas>=1.
      - key: "{{ request.object.spec.replicas || `1` }}"
        operator: GreaterThan
        value: 0
    mutate:
      patchStrategicMerge:
        spec:
          replicas: 1
