apiVersion: sharding.timebertt.dev/v1alpha1
kind: ClusterRing
metadata:
  name: example
spec:
  resources:
  - group: ""
    resource: configmaps
    controlledResources:
    - group: ""
      resource: secrets
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
