apiVersion: sharding.timebertt.dev/v1alpha1
kind: ClusterRing
metadata:
  name: webhosting-operator
spec:
  resources:
  - group: webhosting.timebertt.dev
    resource: websites
    controlledResources:
    - group: apps
      resource: deployments
    - group: ""
      resource: configmaps
    - group: ""
      resource: services
    - group: networking.k8s.io
      resource: ingresses
  namespaceSelector:
    matchLabels:
      webhosting.timebertt.dev/project: "true"
