apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: webhosting-operator
  namespace: webhosting-system
  files:
  - config.yaml

patches:
- path: manager_patch.yaml
